### ISSUE TITLE
Failed to detect the events

### ISSUE THREAD

**Issue by lifeiteng** [merlresearch/sebbs#3]
`Applause` threshold `0.2971`

```
0.00 11.20 0.00 False
11.56 165.02 0.03 False   # failed here
165.28 165.64 0.38 True
165.76 173.96 0.70 True
174.12 299.72 0.00 False
```

![Introducing_GPT-4o_5mins_strong_456_cSEBBSv2_bestCBF](https://github.com/user-attachments/assets/62b5e8b0-d44f-4986-a71e-d29e52d9efa9)

**Comment by lifeiteng** [comment]
solved, I used a larger `step_filter_length`.

**Comment by Hari-Durai-Baskar** [comment]
> `Applause` threshold `0.2971`
> 
> ```
> 0.00 11.20 0.00 False
> 11.56 165.02 0.03 False   # failed here
> 165.28 165.64 0.38 True
> 165.76 173.96 0.70 True
> 174.12 299.72 0.00 False
> ```
> 
> ![Introducing_GPT-4o_5mins_strong_456_cSEBBSv2_bestCBF](https://github.com/user-attachments/assets/62b5e8b0-d44f-4986-a71e-d29e52d9efa9)

Hi @lifeiteng,

how were you able to do this inference? I don't see any inference code available in the repo.

**Comment by lifeiteng** [comment]
@Hari-Durai-Baskar I used other repo: https://github.com/Audio-WestlakeU/audiossl, you should follow: https://github.com/Audio-WestlakeU/audiossl/pull/13

**Comment by Hari-Durai-Baskar** [comment]
Thank you, for the direction.
What about the checkpoint for SEBBS? how to access it?

**Comment by lifeiteng** [comment]
> Thank you, for the direction. What about the checkpoint for SEBBS? how to access it?

I trained it(on a selected AED data eval set) by myself.
